### ISSUE TITLE
How to deploy the server on cloud? 

### ISSUE THREAD

**Issue by AlexanderAzharjan** [Ezharjan/FunBag#2]
I faced some troubles while deploying the server side even directly using XAMPP mirror in Cent OS, how can I fix it?

**Comment by Ezharjan** [comment]
What problems did you face? Can you show me the details?

**Comment by AlexanderAzharjan** [comment]
All most all the troubles lays on deploying the database.

**Comment by Ezharjan** [comment]
Click [here](https://blog.csdn.net/weixin_43867242/article/details/105876872) or [here](https://www.cnblogs.com/ezhar/p/12813490.html) to see the deployment detail. Hope it would help you!
